/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTerrainRouteImport } from './routes/_authenticated/terrain'
import { Route as AuthenticatedStatistiquesRouteImport } from './routes/_authenticated/statistiques'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedPlanningRouteImport } from './routes/_authenticated/planning'
import { Route as AuthenticatedInformationsRouteImport } from './routes/_authenticated/informations'
import { Route as AuthenticatedDemandesRouteImport } from './routes/_authenticated/demandes'
import { Route as AuthenticatedDechetsRouteImport } from './routes/_authenticated/dechets'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedClesRouteImport } from './routes/_authenticated/cles'
import { Route as AuthenticatedChantiersRouteImport } from './routes/_authenticated/chantiers'
import { Route as AuthenticatedInformationsIndexRouteImport } from './routes/_authenticated/informations.index'
import { Route as AuthenticatedInformationsParametresRouteImport } from './routes/_authenticated/informations.parametres'
import { Route as AuthenticatedInformationsNouvelleRouteImport } from './routes/_authenticated/informations.nouvelle'
import { Route as AuthenticatedInformationsArchivesRouteImport } from './routes/_authenticated/informations.archives'
import { Route as AuthenticatedInformationsActivesRouteImport } from './routes/_authenticated/informations.actives'
import { Route as AuthenticatedInformationsIdRouteImport } from './routes/_authenticated/informations.$id'
import { Route as AuthenticatedChantiersIdRouteImport } from './routes/_authenticated/chantiers.$id'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'
import { Route as AuthenticatedAdminEntreprisesRouteImport } from './routes/_authenticated/admin/entreprises'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTerrainRoute = AuthenticatedTerrainRouteImport.update({
  id: '/terrain',
  path: '/terrain',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedStatistiquesRoute =
  AuthenticatedStatistiquesRouteImport.update({
    id: '/statistiques',
    path: '/statistiques',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPlanningRoute = AuthenticatedPlanningRouteImport.update({
  id: '/planning',
  path: '/planning',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInformationsRoute =
  AuthenticatedInformationsRouteImport.update({
    id: '/informations',
    path: '/informations',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDemandesRoute = AuthenticatedDemandesRouteImport.update({
  id: '/demandes',
  path: '/demandes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDechetsRoute = AuthenticatedDechetsRouteImport.update({
  id: '/dechets',
  path: '/dechets',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedClesRoute = AuthenticatedClesRouteImport.update({
  id: '/cles',
  path: '/cles',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedChantiersRoute = AuthenticatedChantiersRouteImport.update({
  id: '/chantiers',
  path: '/chantiers',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInformationsIndexRoute =
  AuthenticatedInformationsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedInformationsRoute,
  } as any)
const AuthenticatedInformationsParametresRoute =
  AuthenticatedInformationsParametresRouteImport.update({
    id: '/parametres',
    path: '/parametres',
    getParentRoute: () => AuthenticatedInformationsRoute,
  } as any)
const AuthenticatedInformationsNouvelleRoute =
  AuthenticatedInformationsNouvelleRouteImport.update({
    id: '/nouvelle',
    path: '/nouvelle',
    getParentRoute: () => AuthenticatedInformationsRoute,
  } as any)
const AuthenticatedInformationsArchivesRoute =
  AuthenticatedInformationsArchivesRouteImport.update({
    id: '/archives',
    path: '/archives',
    getParentRoute: () => AuthenticatedInformationsRoute,
  } as any)
const AuthenticatedInformationsActivesRoute =
  AuthenticatedInformationsActivesRouteImport.update({
    id: '/actives',
    path: '/actives',
    getParentRoute: () => AuthenticatedInformationsRoute,
  } as any)
const AuthenticatedInformationsIdRoute =
  AuthenticatedInformationsIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedInformationsRoute,
  } as any)
const AuthenticatedChantiersIdRoute =
  AuthenticatedChantiersIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedChantiersRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminEntreprisesRoute =
  AuthenticatedAdminEntreprisesRouteImport.update({
    id: '/admin/entreprises',
    path: '/admin/entreprises',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/chantiers': typeof AuthenticatedChantiersRouteWithChildren
  '/cles': typeof AuthenticatedClesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/dechets': typeof AuthenticatedDechetsRoute
  '/demandes': typeof AuthenticatedDemandesRoute
  '/informations': typeof AuthenticatedInformationsRouteWithChildren
  '/planning': typeof AuthenticatedPlanningRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/statistiques': typeof AuthenticatedStatistiquesRoute
  '/terrain': typeof AuthenticatedTerrainRoute
  '/admin/entreprises': typeof AuthenticatedAdminEntreprisesRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/chantiers/$id': typeof AuthenticatedChantiersIdRoute
  '/informations/$id': typeof AuthenticatedInformationsIdRoute
  '/informations/actives': typeof AuthenticatedInformationsActivesRoute
  '/informations/archives': typeof AuthenticatedInformationsArchivesRoute
  '/informations/nouvelle': typeof AuthenticatedInformationsNouvelleRoute
  '/informations/parametres': typeof AuthenticatedInformationsParametresRoute
  '/informations/': typeof AuthenticatedInformationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/chantiers': typeof AuthenticatedChantiersRouteWithChildren
  '/cles': typeof AuthenticatedClesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/dechets': typeof AuthenticatedDechetsRoute
  '/demandes': typeof AuthenticatedDemandesRoute
  '/planning': typeof AuthenticatedPlanningRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/statistiques': typeof AuthenticatedStatistiquesRoute
  '/terrain': typeof AuthenticatedTerrainRoute
  '/admin/entreprises': typeof AuthenticatedAdminEntreprisesRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/chantiers/$id': typeof AuthenticatedChantiersIdRoute
  '/informations/$id': typeof AuthenticatedInformationsIdRoute
  '/informations/actives': typeof AuthenticatedInformationsActivesRoute
  '/informations/archives': typeof AuthenticatedInformationsArchivesRoute
  '/informations/nouvelle': typeof AuthenticatedInformationsNouvelleRoute
  '/informations/parametres': typeof AuthenticatedInformationsParametresRoute
  '/informations': typeof AuthenticatedInformationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_authenticated/chantiers': typeof AuthenticatedChantiersRouteWithChildren
  '/_authenticated/cles': typeof AuthenticatedClesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/dechets': typeof AuthenticatedDechetsRoute
  '/_authenticated/demandes': typeof AuthenticatedDemandesRoute
  '/_authenticated/informations': typeof AuthenticatedInformationsRouteWithChildren
  '/_authenticated/planning': typeof AuthenticatedPlanningRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/statistiques': typeof AuthenticatedStatistiquesRoute
  '/_authenticated/terrain': typeof AuthenticatedTerrainRoute
  '/_authenticated/admin/entreprises': typeof AuthenticatedAdminEntreprisesRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/chantiers/$id': typeof AuthenticatedChantiersIdRoute
  '/_authenticated/informations/$id': typeof AuthenticatedInformationsIdRoute
  '/_authenticated/informations/actives': typeof AuthenticatedInformationsActivesRoute
  '/_authenticated/informations/archives': typeof AuthenticatedInformationsArchivesRoute
  '/_authenticated/informations/nouvelle': typeof AuthenticatedInformationsNouvelleRoute
  '/_authenticated/informations/parametres': typeof AuthenticatedInformationsParametresRoute
  '/_authenticated/informations/': typeof AuthenticatedInformationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/chantiers'
    | '/cles'
    | '/dashboard'
    | '/dechets'
    | '/demandes'
    | '/informations'
    | '/planning'
    | '/profile'
    | '/statistiques'
    | '/terrain'
    | '/admin/entreprises'
    | '/admin/users'
    | '/chantiers/$id'
    | '/informations/$id'
    | '/informations/actives'
    | '/informations/archives'
    | '/informations/nouvelle'
    | '/informations/parametres'
    | '/informations/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/chantiers'
    | '/cles'
    | '/dashboard'
    | '/dechets'
    | '/demandes'
    | '/planning'
    | '/profile'
    | '/statistiques'
    | '/terrain'
    | '/admin/entreprises'
    | '/admin/users'
    | '/chantiers/$id'
    | '/informations/$id'
    | '/informations/actives'
    | '/informations/archives'
    | '/informations/nouvelle'
    | '/informations/parametres'
    | '/informations'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/_authenticated/chantiers'
    | '/_authenticated/cles'
    | '/_authenticated/dashboard'
    | '/_authenticated/dechets'
    | '/_authenticated/demandes'
    | '/_authenticated/informations'
    | '/_authenticated/planning'
    | '/_authenticated/profile'
    | '/_authenticated/statistiques'
    | '/_authenticated/terrain'
    | '/_authenticated/admin/entreprises'
    | '/_authenticated/admin/users'
    | '/_authenticated/chantiers/$id'
    | '/_authenticated/informations/$id'
    | '/_authenticated/informations/actives'
    | '/_authenticated/informations/archives'
    | '/_authenticated/informations/nouvelle'
    | '/_authenticated/informations/parametres'
    | '/_authenticated/informations/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/terrain': {
      id: '/_authenticated/terrain'
      path: '/terrain'
      fullPath: '/terrain'
      preLoaderRoute: typeof AuthenticatedTerrainRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/statistiques': {
      id: '/_authenticated/statistiques'
      path: '/statistiques'
      fullPath: '/statistiques'
      preLoaderRoute: typeof AuthenticatedStatistiquesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/planning': {
      id: '/_authenticated/planning'
      path: '/planning'
      fullPath: '/planning'
      preLoaderRoute: typeof AuthenticatedPlanningRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/informations': {
      id: '/_authenticated/informations'
      path: '/informations'
      fullPath: '/informations'
      preLoaderRoute: typeof AuthenticatedInformationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/demandes': {
      id: '/_authenticated/demandes'
      path: '/demandes'
      fullPath: '/demandes'
      preLoaderRoute: typeof AuthenticatedDemandesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dechets': {
      id: '/_authenticated/dechets'
      path: '/dechets'
      fullPath: '/dechets'
      preLoaderRoute: typeof AuthenticatedDechetsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/cles': {
      id: '/_authenticated/cles'
      path: '/cles'
      fullPath: '/cles'
      preLoaderRoute: typeof AuthenticatedClesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/chantiers': {
      id: '/_authenticated/chantiers'
      path: '/chantiers'
      fullPath: '/chantiers'
      preLoaderRoute: typeof AuthenticatedChantiersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/informations/': {
      id: '/_authenticated/informations/'
      path: '/'
      fullPath: '/informations/'
      preLoaderRoute: typeof AuthenticatedInformationsIndexRouteImport
      parentRoute: typeof AuthenticatedInformationsRoute
    }
    '/_authenticated/informations/parametres': {
      id: '/_authenticated/informations/parametres'
      path: '/parametres'
      fullPath: '/informations/parametres'
      preLoaderRoute: typeof AuthenticatedInformationsParametresRouteImport
      parentRoute: typeof AuthenticatedInformationsRoute
    }
    '/_authenticated/informations/nouvelle': {
      id: '/_authenticated/informations/nouvelle'
      path: '/nouvelle'
      fullPath: '/informations/nouvelle'
      preLoaderRoute: typeof AuthenticatedInformationsNouvelleRouteImport
      parentRoute: typeof AuthenticatedInformationsRoute
    }
    '/_authenticated/informations/archives': {
      id: '/_authenticated/informations/archives'
      path: '/archives'
      fullPath: '/informations/archives'
      preLoaderRoute: typeof AuthenticatedInformationsArchivesRouteImport
      parentRoute: typeof AuthenticatedInformationsRoute
    }
    '/_authenticated/informations/actives': {
      id: '/_authenticated/informations/actives'
      path: '/actives'
      fullPath: '/informations/actives'
      preLoaderRoute: typeof AuthenticatedInformationsActivesRouteImport
      parentRoute: typeof AuthenticatedInformationsRoute
    }
    '/_authenticated/informations/$id': {
      id: '/_authenticated/informations/$id'
      path: '/$id'
      fullPath: '/informations/$id'
      preLoaderRoute: typeof AuthenticatedInformationsIdRouteImport
      parentRoute: typeof AuthenticatedInformationsRoute
    }
    '/_authenticated/chantiers/$id': {
      id: '/_authenticated/chantiers/$id'
      path: '/$id'
      fullPath: '/chantiers/$id'
      preLoaderRoute: typeof AuthenticatedChantiersIdRouteImport
      parentRoute: typeof AuthenticatedChantiersRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/entreprises': {
      id: '/_authenticated/admin/entreprises'
      path: '/admin/entreprises'
      fullPath: '/admin/entreprises'
      preLoaderRoute: typeof AuthenticatedAdminEntreprisesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedChantiersRouteChildren {
  AuthenticatedChantiersIdRoute: typeof AuthenticatedChantiersIdRoute
}

const AuthenticatedChantiersRouteChildren: AuthenticatedChantiersRouteChildren =
  {
    AuthenticatedChantiersIdRoute: AuthenticatedChantiersIdRoute,
  }

const AuthenticatedChantiersRouteWithChildren =
  AuthenticatedChantiersRoute._addFileChildren(
    AuthenticatedChantiersRouteChildren,
  )

interface AuthenticatedInformationsRouteChildren {
  AuthenticatedInformationsIdRoute: typeof AuthenticatedInformationsIdRoute
  AuthenticatedInformationsActivesRoute: typeof AuthenticatedInformationsActivesRoute
  AuthenticatedInformationsArchivesRoute: typeof AuthenticatedInformationsArchivesRoute
  AuthenticatedInformationsNouvelleRoute: typeof AuthenticatedInformationsNouvelleRoute
  AuthenticatedInformationsParametresRoute: typeof AuthenticatedInformationsParametresRoute
  AuthenticatedInformationsIndexRoute: typeof AuthenticatedInformationsIndexRoute
}

const AuthenticatedInformationsRouteChildren: AuthenticatedInformationsRouteChildren =
  {
    AuthenticatedInformationsIdRoute: AuthenticatedInformationsIdRoute,
    AuthenticatedInformationsActivesRoute:
      AuthenticatedInformationsActivesRoute,
    AuthenticatedInformationsArchivesRoute:
      AuthenticatedInformationsArchivesRoute,
    AuthenticatedInformationsNouvelleRoute:
      AuthenticatedInformationsNouvelleRoute,
    AuthenticatedInformationsParametresRoute:
      AuthenticatedInformationsParametresRoute,
    AuthenticatedInformationsIndexRoute: AuthenticatedInformationsIndexRoute,
  }

const AuthenticatedInformationsRouteWithChildren =
  AuthenticatedInformationsRoute._addFileChildren(
    AuthenticatedInformationsRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedChantiersRoute: typeof AuthenticatedChantiersRouteWithChildren
  AuthenticatedClesRoute: typeof AuthenticatedClesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDechetsRoute: typeof AuthenticatedDechetsRoute
  AuthenticatedDemandesRoute: typeof AuthenticatedDemandesRoute
  AuthenticatedInformationsRoute: typeof AuthenticatedInformationsRouteWithChildren
  AuthenticatedPlanningRoute: typeof AuthenticatedPlanningRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedStatistiquesRoute: typeof AuthenticatedStatistiquesRoute
  AuthenticatedTerrainRoute: typeof AuthenticatedTerrainRoute
  AuthenticatedAdminEntreprisesRoute: typeof AuthenticatedAdminEntreprisesRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedChantiersRoute: AuthenticatedChantiersRouteWithChildren,
  AuthenticatedClesRoute: AuthenticatedClesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDechetsRoute: AuthenticatedDechetsRoute,
  AuthenticatedDemandesRoute: AuthenticatedDemandesRoute,
  AuthenticatedInformationsRoute: AuthenticatedInformationsRouteWithChildren,
  AuthenticatedPlanningRoute: AuthenticatedPlanningRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedStatistiquesRoute: AuthenticatedStatistiquesRoute,
  AuthenticatedTerrainRoute: AuthenticatedTerrainRoute,
  AuthenticatedAdminEntreprisesRoute: AuthenticatedAdminEntreprisesRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
