/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedTerrainRouteImport } from './routes/_authenticated/terrain'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedPlanningRouteImport } from './routes/_authenticated/planning'
import { Route as AuthenticatedDemandesRouteImport } from './routes/_authenticated/demandes'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedChantiersRouteImport } from './routes/_authenticated/chantiers'
import { Route as AuthenticatedChantiersIdRouteImport } from './routes/_authenticated/chantiers.$id'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin/users'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTerrainRoute = AuthenticatedTerrainRouteImport.update({
  id: '/terrain',
  path: '/terrain',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPlanningRoute = AuthenticatedPlanningRouteImport.update({
  id: '/planning',
  path: '/planning',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDemandesRoute = AuthenticatedDemandesRouteImport.update({
  id: '/demandes',
  path: '/demandes',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedChantiersRoute = AuthenticatedChantiersRouteImport.update({
  id: '/chantiers',
  path: '/chantiers',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedChantiersIdRoute =
  AuthenticatedChantiersIdRouteImport.update({
    id: '/$id',
    path: '/$id',
    getParentRoute: () => AuthenticatedChantiersRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => AuthenticatedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/chantiers': typeof AuthenticatedChantiersRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/demandes': typeof AuthenticatedDemandesRoute
  '/planning': typeof AuthenticatedPlanningRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/terrain': typeof AuthenticatedTerrainRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/chantiers/$id': typeof AuthenticatedChantiersIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/chantiers': typeof AuthenticatedChantiersRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/demandes': typeof AuthenticatedDemandesRoute
  '/planning': typeof AuthenticatedPlanningRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/terrain': typeof AuthenticatedTerrainRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/chantiers/$id': typeof AuthenticatedChantiersIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authenticated/chantiers': typeof AuthenticatedChantiersRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/demandes': typeof AuthenticatedDemandesRoute
  '/_authenticated/planning': typeof AuthenticatedPlanningRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/terrain': typeof AuthenticatedTerrainRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/chantiers/$id': typeof AuthenticatedChantiersIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/chantiers'
    | '/dashboard'
    | '/demandes'
    | '/planning'
    | '/profile'
    | '/terrain'
    | '/admin/users'
    | '/chantiers/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/chantiers'
    | '/dashboard'
    | '/demandes'
    | '/planning'
    | '/profile'
    | '/terrain'
    | '/admin/users'
    | '/chantiers/$id'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/signup'
    | '/_authenticated/chantiers'
    | '/_authenticated/dashboard'
    | '/_authenticated/demandes'
    | '/_authenticated/planning'
    | '/_authenticated/profile'
    | '/_authenticated/terrain'
    | '/_authenticated/admin/users'
    | '/_authenticated/chantiers/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/terrain': {
      id: '/_authenticated/terrain'
      path: '/terrain'
      fullPath: '/terrain'
      preLoaderRoute: typeof AuthenticatedTerrainRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/planning': {
      id: '/_authenticated/planning'
      path: '/planning'
      fullPath: '/planning'
      preLoaderRoute: typeof AuthenticatedPlanningRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/demandes': {
      id: '/_authenticated/demandes'
      path: '/demandes'
      fullPath: '/demandes'
      preLoaderRoute: typeof AuthenticatedDemandesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/chantiers': {
      id: '/_authenticated/chantiers'
      path: '/chantiers'
      fullPath: '/chantiers'
      preLoaderRoute: typeof AuthenticatedChantiersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/chantiers/$id': {
      id: '/_authenticated/chantiers/$id'
      path: '/$id'
      fullPath: '/chantiers/$id'
      preLoaderRoute: typeof AuthenticatedChantiersIdRouteImport
      parentRoute: typeof AuthenticatedChantiersRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedChantiersRouteChildren {
  AuthenticatedChantiersIdRoute: typeof AuthenticatedChantiersIdRoute
}

const AuthenticatedChantiersRouteChildren: AuthenticatedChantiersRouteChildren =
  {
    AuthenticatedChantiersIdRoute: AuthenticatedChantiersIdRoute,
  }

const AuthenticatedChantiersRouteWithChildren =
  AuthenticatedChantiersRoute._addFileChildren(
    AuthenticatedChantiersRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedChantiersRoute: typeof AuthenticatedChantiersRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDemandesRoute: typeof AuthenticatedDemandesRoute
  AuthenticatedPlanningRoute: typeof AuthenticatedPlanningRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedTerrainRoute: typeof AuthenticatedTerrainRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedChantiersRoute: AuthenticatedChantiersRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDemandesRoute: AuthenticatedDemandesRoute,
  AuthenticatedPlanningRoute: AuthenticatedPlanningRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedTerrainRoute: AuthenticatedTerrainRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
